### ISSUE TITLE
Confusing user count.

### ISSUE THREAD

**Issue by FiniteSingularity** [matthewbrandt/lurkreveal#19]
Looking at my chat, I am seeing the following:
![image](https://user-images.githubusercontent.com/72580859/143686704-c1ee5ceb-2d44-47b9-b5b8-a3f91d05240e.png)

Notice- there are 3 total users listed, but the user count at the top is 4 users. I suspect this is because I am also currently in chat (and I assume the broadcaster is excluded from the users shown), but from a UI perspective, it is a bit confusing.

**Comment by matthewbrandt** [comment]
Yes this number includes the broadcaster, but the broadcaster isn't shown in the list...we should find a way to show that this "includes" the broadcaster somehow. What do you think would be a good way to do that?

**Comment by matthewbrandt** [comment]
I solved this by updating the text in the header, I think that's the easiest option as users only need to see it once to understand it.
